#!/bin/sh
# This script is called by the lambda execution environment when it receives the very first invocation request.

cd /var/task
LD_LIBRARY_PATH="" /usr/local/julia/bin/julia --project=. handle_requests.jl
